# Generated by Django 5.0.1 on 2024-02-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='barber',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='account.company'),
        ),
    ]
