# Generated by Django 5.0.1 on 2024-02-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_created',
        ),
    ]
